@startuml logical

header
The client device interacts with the user interface to access various 
data stored on the database and API servers. Users can view and create 
recipes, which include fish data represented on a map showing the 
location of different fish species and protected areas.
end header

package "Client Device" {
  [User Interface]
}

database "Database Server" {
  [User Data]
  [Recipe Data]
  [Fish Data]
}

database "API Server" {
  [Map Data]
}


[User Interface] --> [User Data]
[User Interface] --> [Recipe Data]
[User Interface] --> [Fish Data]
[User Interface] --> [Map Data]

@enduml
