@startuml logical

package "MarineChoice System" {
  [MarineChoice Application]
  [Recipe Validation]
  [Database]
}

package "External Services" {
  [Admin Gateway]
}

[MarineChoice Application] -> [Recipe Validation]
[Recipe Validation] -> [Database]
[Recipe Validation] --> [Admin Gateway]

@enduml