@startuml physical

header
The MarineChoice Application interacts with the Recipe Validation 
component. The Recipe Validation component accesses the Database for 
storing and retrieving data and communicates with the Admin Gateway for 
external administrative services.
end header

top to bottom direction

package "MarineChoice System" {
  [MarineChoice Application]
  [Recipe Validation]
  [Database]
}

package "External Services" {
  [Admin Gateway]
}

[MarineChoice Application] -> [Recipe Validation]
[Recipe Validation] -> [Database]
[Recipe Validation] --> [Admin Gateway]

@enduml